"""
CorvusTunnel -- Dual-Server Launcher.

Starts two uvicorn servers in parallel:
  - Public API on 0.0.0.0:8000 (accessible via Cloudflare Tunnel)
  - Internal API on 127.0.0.1:8001 (localhost only, for admin)

Usage:
    python main.py
"""

from __future__ import annotations

import asyncio
import logging
import sys

import uvicorn

# -- Setup logging ---------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-7s | %(name)s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("corvustunnel")


def _print_banner(public_port: int, internal_port: int) -> None:
    """Print a startup banner with configuration summary."""
    banner = f"""
+==============================================================+
|                                                              |
|   CORVUSTUNNEL                                           |
|   AI Agent Control with Voice v0.4.0                     |
|                                                              |
+==============================================================+
|                                                              |
|   [PUBLIC]   http://0.0.0.0:{public_port:<5}                          |
|   [INTERNAL] http://127.0.0.1:{internal_port:<5}                         |
|   [API DOCS] http://localhost:{public_port}/docs                     |
|                                                              |
|   Workspace: /workspace                                      |
|                                                              |
+==============================================================+
"""
    print(banner)


async def _run_servers() -> None:
    """Run both public and internal servers concurrently."""
    from config.settings import get_settings

    settings = get_settings()
    public_port = settings.public_port
    internal_port = settings.internal_port

    # Print banner
    _print_banner(public_port, internal_port)

    logger.info(f"Audit log directory: {settings.audit_log_dir}")

    # Configure uvicorn servers
    public_config = uvicorn.Config(
        "public_app:app",
        host="0.0.0.0",
        port=public_port,
        log_level="info",
        access_log=True,
    )
    internal_config = uvicorn.Config(
        "internal_app:app",
        host="127.0.0.1",
        port=internal_port,
        log_level="info",
        access_log=True,
    )

    public_server = uvicorn.Server(public_config)
    internal_server = uvicorn.Server(internal_config)

    # Run both servers concurrently
    logger.info("Starting dual servers...")

    try:
        await asyncio.gather(
            public_server.serve(),
            internal_server.serve(),
        )
    except (KeyboardInterrupt, SystemExit):
        logger.info("Shutdown signal received")
    finally:
        logger.info("CorvusTunnel stopped")


def main() -> None:
    """Entry point."""
    # Validate environment before starting
    try:
        from config.settings import get_settings
        get_settings()
    except Exception as e:
        print(f"\n[ERROR] Configuration error: {e}")
        print(f"\n[TIP] Set AGENT_TOKEN environment variable.")
        print(f"   In Docker, this is auto-generated by boot.py.")
        sys.exit(1)

    try:
        asyncio.run(_run_servers())
    except KeyboardInterrupt:
        print("\nCorvusTunnel stopped.")


if __name__ == "__main__":
    main()
